#include "core/geometry/BoundingBox.h"
#include "core/mesh/PlyMeshLoader.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QTest>
#include <QUuid>

#include <cmath>
#include <cstring>

using namespace vision3d;

namespace {

void appendUChar(QByteArray& bytes, quint8 value)
{
    bytes.append(static_cast<char>(value));
}

void appendFloatLE(QByteArray& bytes, float value)
{
    quint32 bits = 0;
    std::memcpy(&bits, &value, sizeof(value));
    bytes.append(static_cast<char>(bits & 0xffu));
    bytes.append(static_cast<char>((bits >> 8) & 0xffu));
    bytes.append(static_cast<char>((bits >> 16) & 0xffu));
    bytes.append(static_cast<char>((bits >> 24) & 0xffu));
}

void appendInt32LE(QByteArray& bytes, qint32 value)
{
    quint32 bits = 0;
    std::memcpy(&bits, &value, sizeof(value));
    bytes.append(static_cast<char>(bits & 0xffu));
    bytes.append(static_cast<char>((bits >> 8) & 0xffu));
    bytes.append(static_cast<char>((bits >> 16) & 0xffu));
    bytes.append(static_cast<char>((bits >> 24) & 0xffu));
}

QByteArray makeHeader(
    quint32 vertexCount,
    const QByteArray& vertexProperties,
    bool includeFace = true,
    quint32 faceCount = 1,
    const QByteArray& faceProperties = "property list uchar int vertex_indices\n",
    const QByteArray& format = "binary_little_endian")
{
    QByteArray header;
    header += "ply\n";
    header += "format ";
    header += format;
    header += " 1.0\n";
    header += "comment generated by Stage 4B-1 tests\n";
    header += "element vertex ";
    header += QByteArray::number(vertexCount);
    header += "\n";
    header += vertexProperties;
    if (includeFace) {
        header += "element face ";
        header += QByteArray::number(faceCount);
        header += "\n";
        header += faceProperties;
    }
    header += "end_header\n";
    return header;
}

class MeshLoaderTest final : public QObject
{
    Q_OBJECT

private slots:
    void initTestCase();
    void cleanupTestCase();

    void validTriangleMesh();
    void multipleTriangles();
    void propertyOrder();
    void valuePropertyIgnoredSafely();
    void invalidMagic();
    void asciiUnsupported();
    void truncatedFile();
    void invalidVertexIndex();
    void nonTriangleFace();
    void degenerateTriangle();
    void boundingBox();
    void sourceCoordinatePreservation();
    void realPoissonSmoke();

private:
    QString writeFixture(const QString& name, const QByteArray& header, const QByteArray& payload);
    QString m_root;
};

void MeshLoaderTest::initTestCase()
{
    const QString configuredRoot = qEnvironmentVariable("STAGE4B1_TEST_ROOT");
    const QString baseRoot = configuredRoot.isEmpty()
        ? QDir(QCoreApplication::applicationDirPath()).filePath(QStringLiteral("stage4b1_fixtures"))
        : configuredRoot;
    m_root = QDir(baseRoot).filePath(
        QStringLiteral("run_%1").arg(QUuid::createUuid().toString(QUuid::WithoutBraces)));
    QVERIFY2(QDir().mkpath(m_root), qPrintable(m_root));
}

void MeshLoaderTest::cleanupTestCase()
{
    if (!m_root.isEmpty()) {
        QVERIFY2(QDir(m_root).removeRecursively(), qPrintable(m_root));
    }
}

QString MeshLoaderTest::writeFixture(
    const QString& name,
    const QByteArray& header,
    const QByteArray& payload)
{
    const QString path = QDir(m_root).filePath(name + QStringLiteral(".ply"));
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly)) {
        return {};
    }
    if (file.write(header) != header.size() || file.write(payload) != payload.size()) {
        return {};
    }
    file.close();
    return path;
}

void MeshLoaderTest::validTriangleMesh()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n";
    QByteArray payload;
    appendFloatLE(payload, 10.0f);
    appendFloatLE(payload, -20.0f);
    appendFloatLE(payload, 30.0f);
    appendUChar(payload, 255);
    appendUChar(payload, 0);
    appendUChar(payload, 0);
    appendFloatLE(payload, 12.0f);
    appendFloatLE(payload, -20.0f);
    appendFloatLE(payload, 30.0f);
    appendUChar(payload, 0);
    appendUChar(payload, 255);
    appendUChar(payload, 0);
    appendFloatLE(payload, 10.0f);
    appendFloatLE(payload, -18.0f);
    appendFloatLE(payload, 30.0f);
    appendUChar(payload, 0);
    appendUChar(payload, 0);
    appendUChar(payload, 255);
    appendUChar(payload, 3);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 1);
    appendInt32LE(payload, 2);

    const QString path = writeFixture(QStringLiteral("valid_triangle"), makeHeader(3, properties), payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY2(result.success, qPrintable(result.message));
    QCOMPARE(result.mesh.vertices.size(), qsizetype(3));
    QCOMPARE(result.mesh.triangleCount(), qsizetype(1));
    QCOMPARE(result.mesh.indices, QVector<quint32>({0, 1, 2}));
    QVERIFY(result.mesh.hasColors);
    QVERIFY(result.mesh.hasNormals);
    QVERIFY(result.mesh.normalsDerived);
    QCOMPARE(result.mesh.vertices.at(0).color.red, quint8(255));
    QCOMPARE(result.mesh.vertices.at(1).color.green, quint8(255));
    QCOMPARE(result.mesh.vertices.at(2).color.blue, quint8(255));
    QCOMPARE(result.mesh.boundingBox.minimum(), QVector3D(10.0f, -20.0f, 30.0f));
    QCOMPARE(result.mesh.boundingBox.maximum(), QVector3D(12.0f, -18.0f, 30.0f));
    QCOMPARE(result.mesh.boundingBox.center(), QVector3D(11.0f, -19.0f, 30.0f));
    QCOMPARE(result.mesh.boundingBox.extent(), QVector3D(2.0f, 2.0f, 0.0f));
    QVERIFY(qAbs(result.mesh.vertices.at(0).normal.z() - 1.0f) < 1.0e-5f);
}

void MeshLoaderTest::multipleTriangles()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n";
    QByteArray payload;
    const QVector<QVector3D> positions = {
        QVector3D(0.0f, 0.0f, 0.0f),
        QVector3D(1.0f, 0.0f, 0.0f),
        QVector3D(1.0f, 1.0f, 0.0f),
        QVector3D(0.0f, 1.0f, 0.0f)
    };
    for (const QVector3D& position : positions) {
        appendFloatLE(payload, position.x());
        appendFloatLE(payload, position.y());
        appendFloatLE(payload, position.z());
    }
    appendUChar(payload, 3);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 1);
    appendInt32LE(payload, 2);
    appendUChar(payload, 3);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 2);
    appendInt32LE(payload, 3);

    const QString path = writeFixture(
        QStringLiteral("multiple_triangles"),
        makeHeader(4, properties, true, 2),
        payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY2(result.success, qPrintable(result.message));
    QCOMPARE(result.mesh.triangleCount(), qsizetype(2));
    QCOMPARE(result.mesh.indices, QVector<quint32>({0, 1, 2, 0, 2, 3}));
    QVERIFY(result.mesh.hasNormals);
    for (const MeshVertex& vertex : result.mesh.vertices) {
        QVERIFY(vertex.normal.z() > 0.99f);
        QVERIFY(std::isfinite(vertex.normal.x()));
        QVERIFY(std::isfinite(vertex.normal.y()));
        QVERIFY(std::isfinite(vertex.normal.z()));
    }
}

void MeshLoaderTest::propertyOrder()
{
    const QByteArray properties =
        "property uchar red\n"
        "property float value\n"
        "property float z\n"
        "property uchar green\n"
        "property float x\n"
        "property uchar blue\n"
        "property float y\n";
    QByteArray payload;
    appendUChar(payload, 11);
    appendFloatLE(payload, 101.0f);
    appendFloatLE(payload, 3.0f);
    appendUChar(payload, 22);
    appendFloatLE(payload, 1.0f);
    appendUChar(payload, 33);
    appendFloatLE(payload, 2.0f);
    appendUChar(payload, 44);
    appendFloatLE(payload, 202.0f);
    appendFloatLE(payload, 6.0f);
    appendUChar(payload, 55);
    appendFloatLE(payload, 4.0f);
    appendUChar(payload, 66);
    appendFloatLE(payload, 5.0f);
    appendUChar(payload, 77);
    appendFloatLE(payload, 303.0f);
    appendFloatLE(payload, 9.0f);
    appendUChar(payload, 88);
    appendFloatLE(payload, 7.0f);
    appendUChar(payload, 99);
    appendFloatLE(payload, 8.0f);
    appendUChar(payload, 3);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 1);
    appendInt32LE(payload, 2);

    const QString path = writeFixture(QStringLiteral("property_order"), makeHeader(3, properties), payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY2(result.success, qPrintable(result.message));
    QCOMPARE(result.mesh.vertices.at(0).position, QVector3D(1.0f, 2.0f, 3.0f));
    QCOMPARE(result.mesh.vertices.at(1).position, QVector3D(4.0f, 5.0f, 6.0f));
    QCOMPARE(result.mesh.vertices.at(2).position, QVector3D(7.0f, 8.0f, 9.0f));
    QCOMPARE(result.mesh.vertices.at(0).color.red, quint8(11));
    QCOMPARE(result.mesh.vertices.at(1).color.green, quint8(55));
    QCOMPARE(result.mesh.vertices.at(2).color.blue, quint8(99));
}

void MeshLoaderTest::valuePropertyIgnoredSafely()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "property float value\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n";
    QByteArray payload;
    for (int vertexIndex = 0; vertexIndex < 3; ++vertexIndex) {
        appendFloatLE(payload, 20.0f + vertexIndex);
        appendFloatLE(payload, 30.0f + vertexIndex);
        appendFloatLE(payload, 40.0f + vertexIndex);
        appendFloatLE(payload, 900.0f + vertexIndex);
        appendUChar(payload, static_cast<quint8>(10 + vertexIndex));
        appendUChar(payload, static_cast<quint8>(20 + vertexIndex));
        appendUChar(payload, static_cast<quint8>(30 + vertexIndex));
    }
    appendUChar(payload, 3);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 1);
    appendInt32LE(payload, 2);

    const QString path = writeFixture(
        QStringLiteral("value_property"),
        makeHeader(3, properties),
        payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY2(result.success, qPrintable(result.message));
    QVERIFY(result.mesh.hasColors);
    QCOMPARE(result.mesh.vertices.at(0).color.red, quint8(10));
    QCOMPARE(result.mesh.vertices.at(1).color.green, quint8(21));
    QCOMPARE(result.mesh.vertices.at(2).color.blue, quint8(32));
    QCOMPARE(result.mesh.indices.size(), qsizetype(3));
}

void MeshLoaderTest::invalidMagic()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n";
    QByteArray header = makeHeader(3, properties);
    header.replace(0, 3, "nope");

    const QString path = writeFixture(QStringLiteral("invalid_magic"), header, {});
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY(!result.success);
    QCOMPARE(result.errorCode, MeshLoadError::InvalidHeader);
}

void MeshLoaderTest::asciiUnsupported()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n";
    const QString path = writeFixture(
        QStringLiteral("ascii"),
        makeHeader(3, properties, true, 1, "property list uchar int vertex_indices\n", "ascii"),
        {});
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY(!result.success);
    QCOMPARE(result.errorCode, MeshLoadError::UnsupportedFormat);
}

void MeshLoaderTest::truncatedFile()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n";
    QByteArray payload;
    appendFloatLE(payload, 1.0f);
    appendFloatLE(payload, 2.0f);

    const QString path = writeFixture(
        QStringLiteral("truncated"),
        makeHeader(3, properties),
        payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY(!result.success);
    QCOMPARE(result.errorCode, MeshLoadError::UnexpectedEOF);
}

void MeshLoaderTest::invalidVertexIndex()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n";
    QByteArray payload;
    for (int vertexIndex = 0; vertexIndex < 3; ++vertexIndex) {
        appendFloatLE(payload, static_cast<float>(vertexIndex));
        appendFloatLE(payload, 0.0f);
        appendFloatLE(payload, 0.0f);
    }
    appendUChar(payload, 3);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 1);
    appendInt32LE(payload, 3);

    const QString path = writeFixture(
        QStringLiteral("invalid_index"),
        makeHeader(3, properties),
        payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY(!result.success);
    QCOMPARE(result.errorCode, MeshLoadError::InvalidVertexIndex);
}

void MeshLoaderTest::nonTriangleFace()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n";
    QByteArray payload;
    for (int vertexIndex = 0; vertexIndex < 4; ++vertexIndex) {
        appendFloatLE(payload, static_cast<float>(vertexIndex));
        appendFloatLE(payload, 0.0f);
        appendFloatLE(payload, 0.0f);
    }
    appendUChar(payload, 4);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 1);
    appendInt32LE(payload, 2);
    appendInt32LE(payload, 3);

    const QString path = writeFixture(
        QStringLiteral("non_triangle"),
        makeHeader(4, properties),
        payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY(!result.success);
    QCOMPARE(result.errorCode, MeshLoadError::NonTriangleFace);
}

void MeshLoaderTest::degenerateTriangle()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n";
    QByteArray payload;
    for (int vertexIndex = 0; vertexIndex < 3; ++vertexIndex) {
        appendFloatLE(payload, static_cast<float>(vertexIndex));
        appendFloatLE(payload, 0.0f);
        appendFloatLE(payload, 0.0f);
    }
    appendUChar(payload, 3);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 1);
    appendInt32LE(payload, 2);

    const QString path = writeFixture(
        QStringLiteral("degenerate"),
        makeHeader(3, properties),
        payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY2(result.success, qPrintable(result.message));
    QVERIFY(result.mesh.hasNormals);
    for (const MeshVertex& vertex : result.mesh.vertices) {
        QVERIFY(std::isfinite(vertex.normal.x()));
        QVERIFY(std::isfinite(vertex.normal.y()));
        QVERIFY(std::isfinite(vertex.normal.z()));
        QVERIFY(qAbs(vertex.normal.length() - 1.0f) < 1.0e-5f);
    }
}

void MeshLoaderTest::boundingBox()
{
    BoundingBox box;
    QVERIFY(box.isEmpty());
    QCOMPARE(box.center(), QVector3D(0.0f, 0.0f, 0.0f));
    QCOMPARE(box.extent(), QVector3D(0.0f, 0.0f, 0.0f));

    box.expand(QVector3D(5.0f, -2.0f, 10.0f));
    box.expand(QVector3D(-1.0f, 4.0f, 3.0f));
    QVERIFY(!box.isEmpty());
    QCOMPARE(box.minimum(), QVector3D(-1.0f, -2.0f, 3.0f));
    QCOMPARE(box.maximum(), QVector3D(5.0f, 4.0f, 10.0f));
    QCOMPARE(box.center(), QVector3D(2.0f, 1.0f, 6.5f));
    QCOMPARE(box.extent(), QVector3D(6.0f, 6.0f, 7.0f));

    box.reset();
    QVERIFY(box.isEmpty());
}

void MeshLoaderTest::sourceCoordinatePreservation()
{
    const QByteArray properties =
        "property float x\n"
        "property float y\n"
        "property float z\n";
    const QVector<QVector3D> sourcePositions = {
        QVector3D(123.5f, -456.25f, 0.125f),
        QVector3D(124.5f, -456.25f, 0.125f),
        QVector3D(123.5f, -455.25f, 0.125f)
    };
    QByteArray payload;
    for (const QVector3D& position : sourcePositions) {
        appendFloatLE(payload, position.x());
        appendFloatLE(payload, position.y());
        appendFloatLE(payload, position.z());
    }
    appendUChar(payload, 3);
    appendInt32LE(payload, 0);
    appendInt32LE(payload, 1);
    appendInt32LE(payload, 2);

    const QString path = writeFixture(
        QStringLiteral("source_coordinates"),
        makeHeader(3, properties),
        payload);
    QVERIFY(!path.isEmpty());

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY2(result.success, qPrintable(result.message));
    QCOMPARE(result.mesh.vertices.size(), qsizetype(3));
    for (int index = 0; index < sourcePositions.size(); ++index) {
        const QVector3D actual = result.mesh.vertices.at(index).position;
        const QVector3D expected = sourcePositions.at(index);
        QVERIFY(qAbs(actual.x() - expected.x()) < 1.0e-6f);
        QVERIFY(qAbs(actual.y() - expected.y()) < 1.0e-6f);
        QVERIFY(qAbs(actual.z() - expected.z()) < 1.0e-6f);
    }
    QCOMPARE(result.mesh.boundingBox.minimum(), QVector3D(123.5f, -456.25f, 0.125f));
    QCOMPARE(result.mesh.boundingBox.maximum(), QVector3D(124.5f, -455.25f, 0.125f));
}

void MeshLoaderTest::realPoissonSmoke()
{
    const QString path = qEnvironmentVariable("STAGE4B1_REAL_PLY");
    if (path.isEmpty()) {
        QSKIP("STAGE4B1_REAL_PLY is not set; real Poisson smoke is opt-in");
    }
    if (!QFileInfo::exists(path)) {
        QSKIP(qPrintable(QStringLiteral("real Poisson file does not exist: %1").arg(path)));
    }

    const MeshLoadResult result = PlyMeshLoader::load(path);
    QVERIFY2(result.success, qPrintable(result.message));
    QCOMPARE(result.mesh.vertices.size(), qsizetype(329862));
    QCOMPARE(result.mesh.triangleCount(), qsizetype(635990));
    QVERIFY(result.mesh.hasColors);
    QVERIFY(result.mesh.hasNormals);
    QVERIFY(result.mesh.normalsDerived);
    QVERIFY(!result.mesh.boundingBox.isEmpty());

    qInfo().noquote()
        << QStringLiteral(
               "REAL_POISSON vertices=%1 triangles=%2 load_ms=%3 normal_ms=%4 total_ms=%5 approx_cpu_bytes=%6")
               .arg(result.mesh.vertices.size())
               .arg(result.mesh.triangleCount())
               .arg(result.metrics.loadMilliseconds, 0, 'f', 3)
               .arg(result.metrics.normalGenerationMilliseconds, 0, 'f', 3)
               .arg(result.metrics.totalMilliseconds, 0, 'f', 3)
               .arg(result.metrics.approximateCpuBytes);
}

} // namespace

QTEST_MAIN(MeshLoaderTest)

#include "test_mesh_loader.moc"
